products = [
  {
    id: 1,
    img: "images/headphone-1.png",
    title: 'Headphones Wireless.',
    price: 103.20,
    delPrice: "$123.00",
    amount: 1,
  },
  {
    id: 2,
    img: "images/headphone-5.png",
    title: 'Gaming Headphone',
    price: 123,
    delPrice: "$123.00",
    amount: 1,
  },
  {
    id: 3,
    img: "images/headphone-8.png",
    title: 'Headphone with Mic',
    price: 110,
    delPrice: "$123.00",
    amount: 1,
  },
  {
    id: 4,
    img: "images/mobile-1.png",
    title: "Galaxy Android Tablet",
    price: 50,
    delPrice: "$288.00",
    amount: 1,
  },
  {
    id: 5,
    img: "images/mobile-5.png",
    title: "iPhone 14 Pro",
    price: 949.05,
    delPrice: "$999.00",
    amount: 1,
  },
  {
    id: 6,
    img: "images/ipad-1.png",
    title: "Product Name Goes Here",
    price: 90,
    delPrice: "$123.00",
    amount: 1,
  },
  {
    id: 7,
    img: "images/cpu-1.png",
    title: "Product Name Goes Here",
    price: 150,
    delPrice: "$123.00",
    amount: 1,
  },
  {
    id: 8,
    img: "images/cpu-5.png",
    title: "Product Name Goes Here",
    price: 100,
    delPrice: "$123.00",
    amount: 1,
  },
];


let categoryProducts = [
  {
    id: "category_1",
    name: "category name",
    img: "images/headphone-1.png",
    desc: "100 products",
  },
  {
    id: "category_2",
    name: "category name",
    img: "images/headphone-5.png",
    desc: "100 products",
  },
  {
    id: "category_3",
    name: "category name",
    img: "images/headphone-8.png",
    desc: "100 products",
  },
  {
    id: "category_4",
    name: "category name",
    img: "images/cpu-1.png",
    desc: "100 products",
  },
  {
    id: "category_5",
    name: "category name",
    img: "images/cpu-5.png",
    desc: "100 products",
  },
  {
    id: "category_6",
    name: "category name",
    img: "images/ipad-1.png",
    desc: "100 products",
  },
  {
    id: "category_7",
    name: "category name",
    img: "images/mobile-1.png",
    desc: "100 products",
  },
  {
    id: "category_8",
    name: "category name",
    img: "images/mobile-5.png",
    desc: "100 products",
  },
  {
    id: "category_9",
    name: "category name",
    img: "images/watch-1.png",
    desc: "100 products",
  },
  {
    id: "category_10",
    name: "category name",
    img: "images/watch-5.png",
    desc: "100 products",
  },
  ,
  {
    id: "category_11",
    name: "category name",
    img: "images/watch-9.png",
    desc: "100 products",
  },
  ,
  {
    id: "category_12",
    name: "category name",
    img: "images/blutooth-4.png",
    desc: "100 products",
  },
];